learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('user/', include('users.urls', namespace='users'))
]

handler404 = 'learning_logs.views.page_not_found'
handler500 = 'learning_logs.views.page_error'

learning_logs/urls.py
from django.urls import path, include


from learning_logs import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:id>/', views.topic, name='topic'),
    path('new_topics/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path('personal_topic/', views.personal_topic, name='personal_topic'),

]

app_name = 'learning_logs'

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include

from users import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register,name='register')
]

app_name = 'users'

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    brief = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField()

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    class Mete:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + "..."
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from learning_logs.models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','brief','public']
        labels = {'text':'','brief':'','public':'公开'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from learning_logs.check import check_topic_owner, check_entry_owner, check_topic_public
from learning_logs.forms import TopicForm, EntryForm
from learning_logs.models import Topic, Entry


def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(public=1).order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, id):
    topic = Topic.objects.get(id=id)
    check_topic_public(request,topic)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        check_topic_public(request,topic)
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_entry_owner(request,entry)
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def page_not_found(request,exception):
    return render(request,'learning_logs/404.html')


def page_error(request,*exception):
    return render(request,'learning_logs/500.html')


@login_required
def personal_topic(request):
    personal_topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'personal_topics':personal_topics}
    return render(request,'learning_logs/personal_topic.html',context)

users/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password = request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request,'users/register.html',context)

templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{%  url 'learning_logs:index' %}">
                    Learning logs
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a> </li>
                    <li><a href="{% url 'learning_logs:personal_topic' %}">Personal Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello,{{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>

                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_entry</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap3 %}
    {% block header %}
        <h2>Edit entry:</h2>
    {% endblock header %}
    {% block content %}
        <form action="{% url 'learning_logs:edit_entry' entry.id %}"method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
             <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button name="submit" class="btn btn-primary">save changes</button>
                <a class="btn btn-primary" role="button" href="{% url 'learning_logs:topic' topic.id %}">back</a>
             </div>
        </form>
    {% endblock content %}
</body>
</html>

templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
    {% endblock header %}
    {% block content %}
        <h2>
        {% if not request.user.is_authenticated %}
        <a href="{% url 'users:register' %}">Register an account</a>
        to make your own Learning Log,and list the topics you're learning
        about.
        {% endif %}
        </h2>
        <h2>
        Whenever you learn something new about a topic,make an entry
        summarizing what you've learned.
        </h2>
    {% endblock content %}
</body>
</html>

templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_entry</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap3 %}
    {% block header %}
        <h2>Add new entry</h2>
    {% endblock header %}
    {% block content %}
        <form action="{% url 'learning_logs:new_entry' topic.id %}"method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <button name="submit" class="btn btn-primary">add entry</button>
                    <a class="btn btn-primary" role="button" href="{% url 'learning_logs:topic' topic.id %}">back</a>
                </div>

        </form>
    {% endblock content %}
</body>
</html>

templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_topic</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap3 %}
    {% block header %}
        <h2>Add a new topic.</h2>
    {% endblock header %}
    {% block content %}
        <form  method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button name="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-primary" role="button" href="{% url 'learning_logs:topics' %}">back</a>
             </div>
        </form>
    {% endblock content %}

</body>
</html>

templates/learning_logs/personal_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>personal_topic</title>
        <style>
        .card {
            position: relative;
            display: flex;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0,0,0,.125);
            border-radius: .25rem;
            margin-bottom: 4rem;
            }
        .card-body {
            flex: 1 1 auto;
            padding: 0 1rem 1rem 1rem;
            }
        .card-header {
            padding: .5rem 1rem;
            margin-top: 0;
            background-color: rgba(0,0,0,.03);
            border-bottom: 1px solid rgba(0,0,0,.125);
            }
        .little-card-text{
            height: 80px;
        }
        .col-sm-4{
            text-align: center;
        }
        .little-card-title {
	        margin-bottom: .5rem;
            margin-top:0;
            font-size: 12px;
            text-align: right;
            font-weight: 500;
        }
    </style>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block header %}
        <h1>Personal Topics</h1>
    {% endblock header %}
    {% block content %}
        <div class="card">
          <div class="card-header">
            Add a new topic
          </div>
          <div class="card-body">
            <p class="card-text">try to add a new one you want to keep it secret.</p>
            <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add</a>
          </div>
        </div>
        {% for topic in personal_topics %}
             <div class="col-sm-4">
                <div class="card" style="width: 18rem;"  >
                    <h5 class="card-header">{{ topic }}</h5>
                  <div class="card-body">
                      {% if topic.public %}
                      <p class="little-card-title"> public</p>
                      {% else %}
                      <p class="little-card-title"> private</p>
                      {% endif %}
                    <p class="little-card-text"><a href="{% url 'learning_logs:topic' topic.id %}" >{{ topic.brief }}</a></p>
                     <div class="card-footer">
                      <small class="text-muted">{{ topic.date_added|date:'M d, Y' }}</small>
                    </div>
                  </div>
                </div>

             </div>
        {% empty %}
        No topic have been added yet
        {% endfor %}

     {% endblock content %}
</body>
</html>

templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title> view topic </title>
        <style>
        .card {
            position: relative;
            display: flex;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0,0,0,.125);
            border-radius: .25rem;
            margin-bottom: 4rem;
            }
        .card-body {
            flex: 1 1 auto;
            padding: 0 1rem 1rem 1rem;
            }
        .card-header {
            padding: .5rem 1rem;
            margin-top: 0;
            background-color: rgba(0,0,0,.03);
            border-bottom: 1px solid rgba(0,0,0,.125);
            }
        .little-card-text{
            height: 3rem;
        }
        .col-sm-4{
            text-align: center;
        }
        .little-card-title {
	        margin-bottom: .5rem;
            margin-top:0;
            font-size: 12px;
            text-align: right;
            font-weight: 500;
        }
    </style>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block header %}
        <h2>{{ topic }}</h2>
    {% endblock header %}
    {% block content %}
        <div class="card">
          <div class="card-header">
            Add a new entry
          </div>
          <div class="card-body">
            <p class="card-text">want to say something with the topic,try to add a new one.</p>
             <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-primary">Add</a>
          </div>
        </div>
        {% for entry in entries %}
               <div class="col-sm-4">
                <div class="card" style="width: 18rem;"  >
                    <h5 class="card-header">{{ entry.owner }}
                        {% if user.username == entry.owner %}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                        </small>
                        {% endif %}
                    </h5>
                  <div class="card-body">
                    <p class="little-card-text">{{ entry.text }}</p>
                     <div class="card-footer">
                      <small class="text-muted">{{ entry.date_added|date:'M d, Y H' }}</small>
                    </div>
                  </div>
                </div>
               </div>
        {% empty %}
                There are no entries for this topic.
        {% endfor %}
    {% endblock content %}

</body>
</html>

templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <style>
        .card {
            position: relative;
            display: flex;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0,0,0,.125);
            border-radius: .25rem;
            margin-bottom: 4rem;
            }
        .card-body {
            flex: 1 1 auto;
            padding: 0 1rem 1rem 1rem;
            }
        .card-header {
            padding: .5rem 1rem;
            margin-top: 0;
            background-color: rgba(0,0,0,.03);
            border-bottom: 1px solid rgba(0,0,0,.125);
            }
        .little-card-text{
            height: 80px;
        }
        .col-sm-4{
            text-align: center;
        }
        .little-card-title {
	        margin-bottom: .5rem;
            margin-top:0;
            font-size: 12px;
            text-align: right;
            font-weight: 500;
        }
    </style>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block header %}
        <h1>Topics</h1>
    {% endblock header %}
    {% block content %}
        <div class="card">
          <div class="card-header">
            Add a new topic
          </div>
          <div class="card-body">
            <p class="card-text">if you can not found what you need,try to add a new one.</p>
            <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add</a>
          </div>
        </div>
        {% for topic in topics %}
             <div class="col-sm-4">
                <div class="card" style="width: 18rem;"  >
                    <h5 class="card-header">{{ topic }}</h5>
                  <div class="card-body">
                      <p class="little-card-title"> {{ topic.owner}}</p>
                    <p class="little-card-text"><a href="{% url 'learning_logs:topic' topic.id %}" >{{ topic.brief }}</a></p>
                     <div class="card-footer">
                      <small class="text-muted">{{ topic.date_added|date:'M d, Y' }}</small>
                    </div>
                  </div>
                </div>

             </div>
        {% empty %}
        No topic have been added yet
        {% endfor %}

     {% endblock content %}
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap3 %}
    {% block header %}
        <h2>Log in to your account.</h2>
    {% endblock header %}
    {% block content %}
        <form  method="post" action="{% url 'users:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-outline-primary">log in</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
        </form>
    {% endblock content %}
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap3 %}
    {% block header %}
        <h2>Register</h2>
    {% endblock header %}
    {% block content %}
        <form  method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-outline-primary">log in</button>
            {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
        </form>
    {% endblock content %}
</body>
</html>